settings:
  APP_DISPLAY_NAME: Notities
  PRODUCTION_APP_NAME: MI-YA
  APP_GROUP_IDENTIFIER: group.nl.kinooz.miya.element
  BASE_BUNDLE_IDENTIFIER: nl.kinooz.miya
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: ""
